pipeline {
   options { disableConcurrentBuilds() }
   agent { label 'dss-plugin-tests'}
   environment {
        SLACK_HOOK=credentials("slack_hook")
    }
   stages {
      stage('Signal slack for daily report') {
         steps {
            sh '''#!/bin/bash
               set -e
               rm -rf ./env
               python3 -m venv env/
               source env/bin/activate
               pip3 install --upgrade pip
               pip install --no-cache-dir requests
               python $WORKSPACE/dku_plugin_test_utils/signal_slack/signal_slack.py $HOME/daily-statuses $SLACK_HOOK
               deactivate
               '''
         }
      }
   }
}